# cexfy override JSON
access_log /opt/hiddify-manager/log/system/cexfy-access.log;
error_log  /opt/hiddify-manager/log/system/cexfy-error.log debug;

location ^~ /zz {
    proxy_pass         http://127.0.0.1:9100;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
}
